/**
 * Tool Manager - Dynamic Python Tool Discovery and Management
 * 
 * Handles:
 * - Manifest synchronization (spawning manifest_updater.py)
 * - Tool discovery from manifests
 * - File system watching for hot-reload
 * - Inventory management
 */

import { app, ipcMain } from 'electron'
import { spawn } from 'node:child_process'
import { join, basename, resolve, relative, sep } from 'node:path'
import { readFile, access, mkdir } from 'node:fs/promises'
import { constants } from 'node:fs'
import chokidar from 'chokidar'

const FEATURE_FLAG = process.env.ENABLE_PYTHON_TOOL_MANAGEMENT === 'true'

type IpcSenderValidator = (frame: Electron.WebFrameMain | null) => boolean

function defaultIpcSenderValidator(frame: Electron.WebFrameMain | null): boolean {
  if (!frame) return false
  const url = new URL(frame.url)
  return url.protocol === 'file:' || url.origin === process.env.ELECTRON_RENDERER_URL
}

// ============================================
// Lazy-evaluated directory paths (to avoid calling app.* before ready)
// ============================================

let _projectRoot: string | null = null
let _toolsDir: string | null = null
let _userCustomToolsDir: string | null = null
let _manifestsDir: string | null = null
let _pythonScriptsDir: string | null = null
let _pythonPath: string | null = null

function getProjectRoot(): string {
  if (_projectRoot === null) {
    _projectRoot = app.isPackaged
      ? join(process.resourcesPath, 'app.asar.unpacked')
      : join(__dirname, '..', '..')
  }
  return _projectRoot
}

function getToolsDir(): string {
  if (_toolsDir === null) {
    _toolsDir = app.isPackaged
      ? join(process.resourcesPath, 'app.asar.unpacked', 'agent', 'tools', 'src', 'strands_tools')
      : join(__dirname, '..', '..', 'agent', 'tools', 'src', 'strands_tools')
  }
  return _toolsDir
}

function getUserCustomToolsDir(): string {
  if (_userCustomToolsDir === null) {
    _userCustomToolsDir = join(app.getPath('userData'), 'custom_tools')
  }
  return _userCustomToolsDir
}

function getManifestsDir(): string {
  if (_manifestsDir === null) {
    _manifestsDir = join(app.getPath('userData'), 'tool_manifests')
  }
  return _manifestsDir
}

function getPythonScriptsDir(): string {
  if (_pythonScriptsDir === null) {
    _pythonScriptsDir = app.isPackaged
      ? join(process.resourcesPath, 'app.asar.unpacked', 'python_scripts')
      : join(__dirname, '..', '..', 'python_scripts')
  }
  return _pythonScriptsDir
}

function getPythonPath(): string {
  if (_pythonPath === null) {
    const venvPython = app.isPackaged
      ? join(process.resourcesPath, 'bundled_python', 'python')
      : join(__dirname, '..', '..', 'venv', 'bin', 'python')
    
    // Fall back to system Python in dev mode only
    if (!app.isPackaged) {
      try {
        require('fs').accessSync(venvPython, constants.X_OK)
        _pythonPath = venvPython
      } catch {
        _pythonPath = process.platform === 'win32' ? 'python' : 'python3'
      }
    } else {
      _pythonPath = venvPython
    }
  }
  return _pythonPath
}

// ============================================
// Types
// ============================================

export interface ToolInfo {
  name: string
  description: string
  version: string
  executableFilename: string
  executablePath: string
  category: string
  argsSchema?: object
  dependencies?: string[]
  autoGenerated?: boolean
}

// ============================================
// State
// ============================================

let discoveredTools: ToolInfo[] = []
let watcher: chokidar.FSWatcher | null = null
let isInitialized = false

// ============================================
// Manifest Synchronization
// ============================================

/**
 * Spawn manifest_updater.py to scan tools and generate manifests.
 */
export async function initializeAndSyncManifests(): Promise<{ success: boolean; error?: string }> {
  if (!FEATURE_FLAG) {
    return { success: true }
  }

  const pythonPath = getPythonPath()
  const updaterScript = join(getPythonScriptsDir(), 'manifest_updater.py')
  const projectRoot = getProjectRoot()
  const manifestsDir = getManifestsDir()
  const customToolsDir = getUserCustomToolsDir()

  // Ensure directories exist
  await mkdir(manifestsDir, { recursive: true })
  await mkdir(customToolsDir, { recursive: true })

  return new Promise((resolve) => {
    console.log('[ToolManager] Syncing manifests...')
    console.log('[ToolManager] Python:', pythonPath)
    console.log('[ToolManager] Script:', updaterScript)
    console.log('[ToolManager] Project root:', projectRoot)
    console.log('[ToolManager] Manifests dir:', manifestsDir)
    console.log('[ToolManager] Custom tools dir:', customToolsDir)

    // Pass: project_root, output_dir, custom_tools_dir
    const proc = spawn(pythonPath, [updaterScript, projectRoot, manifestsDir, customToolsDir])

    let stdout = ''
    let stderr = ''

    proc.stdout.on('data', (data) => {
      stdout += data.toString()
    })

    proc.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    proc.on('close', (code) => {
      if (code === 0) {
        try {
          const result = JSON.parse(stdout)
          console.log(`[ToolManager] Manifest sync complete: ${result.loadable_tools_count} tools discovered`)
          resolve({ success: true })
        } catch {
          console.log('[ToolManager] Manifest sync complete')
          resolve({ success: true })
        }
      } else {
        console.error('[ToolManager] Manifest sync failed:', stderr)
        resolve({ success: false, error: stderr })
      }
    })

    proc.on('error', (err) => {
      console.error('[ToolManager] Failed to spawn manifest updater:', err)
      resolve({ success: false, error: err.message })
    })
  })
}

// ============================================
// Tool Discovery
// ============================================

/**
 * Read the manifest and build the tools inventory.
 */
export async function discoverDynamicToolsForAgent(): Promise<ToolInfo[]> {
  if (!FEATURE_FLAG) {
    return []
  }

  const manifestsDir = getManifestsDir()
  const toolsDir = getToolsDir()
  const tools: ToolInfo[] = []

  try {
    // Read the strands tools manifest
    const manifestPath = join(manifestsDir, 'strands_tools_manifest.json')
    await access(manifestPath, constants.R_OK)
    
    const content = await readFile(manifestPath, 'utf-8')
    const manifest = JSON.parse(content) as {
      generated_at: string
      tools_directory: string
      tool_count: number
      tools: Array<{
        name: string
        description: string
        full_docstring?: string
        executable_filename: string
        args_schema?: object
        version: string
      }>
    }

    for (const tool of manifest.tools) {
      const executablePath = join(toolsDir, tool.executable_filename)
      
      // Validate file exists
      try {
        await access(executablePath, constants.R_OK)
      } catch {
        console.warn(`[ToolManager] Tool file not found: ${executablePath}`)
        continue
      }

      tools.push({
        name: tool.name,
        description: tool.description,
        version: tool.version,
        executableFilename: tool.executable_filename,
        executablePath,
        category: 'strands_tools', // All strands tools in one category
        argsSchema: tool.args_schema
      })
    }
  } catch (err) {
    console.log('[ToolManager] No manifest found yet, run sync first')
  }

  discoveredTools = tools
  console.log(`[ToolManager] Discovered ${tools.length} tools`)
  return tools
}

/**
 * Get the current discovered tools (cached).
 */
export function getDiscoveredTools(): ToolInfo[] {
  return discoveredTools
}

/**
 * Get the full discovery manifest for agent system prompt injection.
 * This tells the agent what tools are available to load.
 */
export async function getFullManifest(): Promise<{
  loadable_tools: Array<{ name: string; description: string; path: string; category: string; load_command: string }>
  mcp_servers: Array<{ id: string; description: string; connect_command: string }>
  openapi_specs: Array<{ name: string; path: string; mcp_command: string }>
} | null> {
  const manifestPath = join(getManifestsDir(), 'tools_discovery_manifest.json')
  
  try {
    const content = await readFile(manifestPath, 'utf-8')
    return JSON.parse(content)
  } catch {
    console.log('[ToolManager] No discovery manifest found')
    return null
  }
}

/**
 * Get the user custom tools directory path.
 * When agent creates a new tool, save it here.
 */
export function getCustomToolsDir(): string {
  return getUserCustomToolsDir()
}

// ============================================
// File System Watcher
// ============================================

/**
 * Start watching the tools directory for changes.
 * Triggers manifest resync and inventory update on file changes.
 */
export function startWatcher(
  onUpdate: (tools: ToolInfo[]) => void
): void {
  if (!FEATURE_FLAG) {
    return
  }

  const toolsDir = getToolsDir()
  const customToolsDir = getUserCustomToolsDir()

  // Close existing watcher if any
  if (watcher) {
    watcher.close()
  }

  console.log(`[ToolManager] Starting file watcher on: ${toolsDir}`)
  console.log(`[ToolManager] Also watching custom tools: ${customToolsDir}`)

  // Watch both the main tools dir and user custom tools dir
  watcher = chokidar.watch([toolsDir, customToolsDir], {
    ignored: /(^|[\/\\])\../, // Ignore dotfiles
    persistent: true,
    depth: 2,
    ignoreInitial: true, // Don't trigger on initial scan
    awaitWriteFinish: {
      stabilityThreshold: 500,
      pollInterval: 100
    }
  })

  // Debounce updates to avoid excessive reprocessing
  let updateTimeout: NodeJS.Timeout | null = null

  const triggerUpdate = async () => {
    if (updateTimeout) {
      clearTimeout(updateTimeout)
    }
    updateTimeout = setTimeout(async () => {
      console.log('[ToolManager] Tools directory changed, resyncing...')
      await initializeAndSyncManifests()
      const tools = await discoverDynamicToolsForAgent()
      onUpdate(tools)
    }, 1000) // Wait 1 second for stability
  }

  watcher
    .on('add', (path) => {
      if (path.endsWith('.py') || path.endsWith('.toolinfo.json')) {
        console.log(`[ToolManager] Tool added: ${basename(path)}`)
        triggerUpdate()
      }
    })
    .on('change', (path) => {
      if (path.endsWith('.py') || path.endsWith('.toolinfo.json')) {
        console.log(`[ToolManager] Tool changed: ${basename(path)}`)
        triggerUpdate()
      }
    })
    .on('unlink', (path) => {
      if (path.endsWith('.py') || path.endsWith('.toolinfo.json')) {
        console.log(`[ToolManager] Tool removed: ${basename(path)}`)
        triggerUpdate()
      }
    })
    .on('error', (error) => {
      console.error('[ToolManager] Watcher error:', error)
    })
}

/**
 * Stop the file watcher.
 */
export function stopWatcher(): void {
  if (watcher) {
    watcher.close()
    watcher = null
  }
}

// ============================================
// Initialization
// ============================================

/**
 * Initialize the tool management system.
 * Should be called once on app ready.
 */
export async function initializeToolManager(
  onInventoryUpdate?: (tools: ToolInfo[]) => void
): Promise<void> {
  if (!FEATURE_FLAG) {
    console.log('[ToolManager] Feature flag disabled, skipping initialization')
    return
  }

  if (isInitialized) {
    console.log('[ToolManager] Already initialized')
    return
  }

  console.log('[ToolManager] Initializing tool management system...')

  // Sync manifests
  await initializeAndSyncManifests()

  // Discover tools
  await discoverDynamicToolsForAgent()

  // Start watching for changes
  if (onInventoryUpdate) {
    startWatcher(onInventoryUpdate)
  }

  isInitialized = true
  console.log('[ToolManager] Initialization complete')
}

// ============================================
// IPC Handlers Registration
// ============================================

/**
 * Register IPC handlers for tool management.
 * Called from main.ts during app setup.
 */
export function registerToolManagerIPC(validateIpcSender: IpcSenderValidator = defaultIpcSenderValidator): void {
  if (!FEATURE_FLAG) {
    return
  }

  ipcMain.handle('tools:discover', async (event) => {
    if (!validateIpcSender(event.senderFrame)) return []
    return await discoverDynamicToolsForAgent()
  })

  ipcMain.handle('tools:refresh', async (event) => {
    if (!validateIpcSender(event.senderFrame)) return []
    await initializeAndSyncManifests()
    return await discoverDynamicToolsForAgent()
  })

  ipcMain.handle('tools:list', (event) => {
    if (!validateIpcSender(event.senderFrame)) return []
    return getDiscoveredTools()
  })

  // Get the full discovery manifest for agent system prompt
  ipcMain.handle('tools:getManifest', async (event) => {
    if (!validateIpcSender(event.senderFrame)) return null
    return await getFullManifest()
  })

  // Get path where custom tools should be saved
  ipcMain.handle('tools:getCustomToolsDir', async (event) => {
    if (!validateIpcSender(event.senderFrame)) return null
    const dir = getCustomToolsDir()
    // Ensure directory exists
    await mkdir(dir, { recursive: true })
    return dir
  })

  // Save a custom tool created by the agent
  ipcMain.handle('tools:saveCustomTool', async (event, name: string, code: string) => {
    if (!validateIpcSender(event.senderFrame)) return { success: false, error: 'Forbidden sender' }
    if (!/^[a-zA-Z0-9_-]{1,64}$/.test(name)) return { success: false, error: 'Invalid tool name' }
    const { writeFile } = await import('node:fs/promises')
    const dir = resolve(getCustomToolsDir())
    await mkdir(dir, { recursive: true })
    const toolPath = resolve(dir, `${name}.py`)
    const rel = relative(dir, toolPath)
    if (rel.startsWith('..') || rel.includes(`..${sep}`)) return { success: false, error: 'Path traversal blocked' }
    await writeFile(toolPath, code, { encoding: 'utf-8', mode: 0o600 })
    return { success: true, path: toolPath }
  })

  console.log('[ToolManager] IPC handlers registered')
}
