import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { Task } from '@/pages/types/task'
import { NotionEditor } from '../editor/NotionEditor'
import { 
  Sparkles as SparklesIcon, 
  ListTodo as ChecklistIcon, 
  Check as CheckIcon, 
  ChevronRight as ChevronRightIcon, 
  Plus as PlusIcon 
} from 'lucide-react'

interface DescriptionTabProps {
  task: Task
  onUpdate?: (task: Task) => void
  onTaskClick?: (taskId: string) => void
}

export function DescriptionTab({ task, onUpdate, onTaskClick }: DescriptionTabProps) {
  const [content, setContent] = useState(task.description || '')
  
  const handleEditorChange = (newContent: string) => {
    setContent(newContent)
  }

  const handleSave = () => {
    if (onUpdate) {
        onUpdate({ ...task, description: content })
    }
  }

  /* Auto-save effect could be added here similar to the plan, but let's stick to explicit save + internal state for now or simple propagation */

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* AI Summary Banner - Glass Variant */}
      {task.autoGeneratedSummary && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="
            flex-shrink-0
            mx-6 mt-4 p-4
            rounded-2xl
            glass-bold
            bg-gradient-to-r from-accent/5 via-accent/10 to-accent/5
            border border-accent/10 dark:border-accent-light/10
          "
        >
          <div className="flex items-start gap-3">
            <span className="
              flex-shrink-0
              w-8 h-8 rounded-lg
              glass-subtle
              flex items-center justify-center
            ">
              <SparklesIcon className="w-4 h-4 text-accent dark:text-accent-light" />
            </span>
            <div className="flex-1 min-w-0">
              <h4 className="
                text-label uppercase tracking-wider
                text-accent dark:text-accent-light
                mb-1 font-bold
              ">
                AI Summary
              </h4>
              <p className="
                text-body-sm
                text-ink-secondary dark:text-ink-inverse-secondary
                leading-relaxed
              ">
                {task.autoGeneratedSummary}
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Document Editor Area */}
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="p-6">
           <NotionEditor 
             content={content}
             onChange={handleEditorChange}
             onSave={handleSave}
             placeholder="Add a detailed description... Type / for commands"
             // Pass users if we had them in context
           />
        </div>
      </div>

      {/* Subtasks Section */}
      <SubtasksSection 
        subtasks={task.subtasks} 
        onUpdate={(newSubtasks) => {
          if (onUpdate) {
            onUpdate({ ...task, subtasks: newSubtasks })
          }
        }}
        onTaskClick={onTaskClick}
      />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// SUBTASKS SECTION (Collapsible)
// ─────────────────────────────────────────────────────────────────────────────

import { SubtaskCreationModal } from '../SubtaskCreationModal'
import { TaskPriority } from '@/pages/types/task'

function SubtasksSection({ 
  subtasks, 
  onUpdate,
  onTaskClick
}: { 
  subtasks: Task['subtasks']
  onUpdate?: (subtasks: Task['subtasks']) => void
  onTaskClick?: (taskId: string) => void 
}) {
  const [isExpanded, setIsExpanded] = useState(true)
  const [isModalOpen, setIsModalOpen] = useState(false)
  
  const completedCount = subtasks.filter(s => s.completed).length
  const percentage = subtasks.length > 0 ? Math.round((completedCount / subtasks.length) * 100) : 0
  
  const handleToggleSubtask = (id: string) => {
    if (!onUpdate) return
    const updated = subtasks.map(s => s.id === id ? { ...s, completed: !s.completed } : s)
    onUpdate(updated)
  }

  const handleCreateSubtask = (title: string, priority?: TaskPriority) => {
    if (!onUpdate) return
    const newSubtask: Task['subtasks'][0] = {
      id: crypto.randomUUID(),
      title,
      completed: false,
      order: subtasks.length,
      priority,
    }
    onUpdate([...subtasks, newSubtask])
  }
  
  return (
    <div className="
      flex-shrink-0
      border-t border-surface-200/50 dark:border-surface-700/50
      glass-frosted
    ">
      {/* Collapsible Header */}
      <div className="flex items-center justify-between px-6 py-4">
        <motion.button
          onClick={() => setIsExpanded(!isExpanded)}
          className="flex items-center gap-2 hover:opacity-80 transition-opacity"
        >
          <motion.div
            animate={{ rotate: isExpanded ? 90 : 0 }}
            transition={{ duration: 0.2 }}
          >
            <ChevronRightIcon className="w-4 h-4 text-ink-muted dark:text-ink-inverse-muted" />
          </motion.div>
          <div className="flex items-center gap-2">
            <ChecklistIcon className="w-4 h-4 text-ink-muted dark:text-ink-inverse-muted" />
            <span className="text-body-sm font-medium text-ink dark:text-ink-inverse">
              Sub-Tasks
            </span>
            <span className="
              px-2 py-0.5 rounded-md
              glass-subtle
              text-label
              text-ink-muted dark:text-ink-inverse-muted
            ">
              {completedCount}/{subtasks.length}
            </span>
          </div>
        </motion.button>

        <div className="flex items-center gap-4">
           {/* Progress % */}
           <span className="text-body-sm font-medium text-accent dark:text-accent-light">
            {percentage}%
          </span>
          {/* Quick Add Button */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setIsModalOpen(true)}
            className="p-1 rounded-md hover:bg-surface-200 dark:hover:bg-surface-700 text-ink-muted hover:text-ink transition-colors"
          >
            <PlusIcon className="w-4 h-4" />
          </motion.button>
        </div>
      </div>

      {/* Collapsible Content */}
      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-4">
              {/* Progress Bar */}
              <div className="h-1.5 rounded-full bg-surface-200/50 dark:bg-surface-700/50 mb-4 overflow-hidden">
                <motion.div
                  className={`h-full rounded-full ${percentage === 100 ? 'bg-success' : 'bg-accent dark:bg-accent-light'}`}
                  initial={{ width: 0 }}
                  animate={{ width: `${percentage}%` }}
                  transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                />
              </div>

              {/* Subtask List */}
              <div className="space-y-1">
                {subtasks.length === 0 ? (
                  <div className="text-center py-6 text-ink-muted dark:text-ink-inverse-muted text-sm italic">
                    No subtasks yet.
                  </div>
                ) : (
                  subtasks.map((subtask, index) => (
                    <motion.div
                      key={subtask.id}
                      initial={{ opacity: 0, x: -8 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.05 }}
                      onClick={() => onTaskClick?.(subtask.id)}
                      className="
                        group
                        relative
                        flex items-center gap-3
                        p-2.5 rounded-xl
                        glass-subtle
                        border border-transparent
                        hover:border-white/10 hover:bg-white/5
                        transition-all duration-200
                        cursor-pointer
                      "
                    >
                      {/* Purple Checkbox */}
                      <motion.button
                        whileTap={{ scale: 0.9 }}
                        onClick={(e) => {
                          e.stopPropagation()
                          handleToggleSubtask(subtask.id)
                        }}
                        className={`
                          flex-shrink-0
                          w-5 h-5 rounded-md
                          flex items-center justify-center
                          border-2
                          transition-colors duration-200
                          ${subtask.completed
                            ? 'bg-accent border-accent dark:bg-accent-light dark:border-accent-light'
                            : 'border-surface-300 dark:border-surface-600 group-hover:border-accent dark:group-hover:border-accent-light'
                          }
                        `}
                      >
                        {subtask.completed && (
                          <CheckIcon className="w-3.5 h-3.5 text-white" strokeWidth={3} />
                        )}
                      </motion.button>
                      
                      {/* Content */}
                      <div className="flex-1 min-w-0 flex items-center justify-between gap-4">
                        <span className={`
                          truncate text-sm font-medium
                          ${subtask.completed
                            ? 'text-ink-muted dark:text-ink-inverse-muted line-through'
                            : 'text-ink dark:text-ink-inverse'
                          }
                        `}>
                          {subtask.title}
                        </span>

                        {/* Metadata Pills */}
                        <div className="flex items-center gap-2 opacity-60 group-hover:opacity-100 transition-opacity">
                          {subtask.priority && (
                             <PriorityBadge priority={subtask.priority} />
                          )}
                          {/* Assignee Avatar (Placeholder if none) */}
                          <div className="w-5 h-5 rounded-full bg-surface-200 dark:bg-surface-700 border border-white/10 flex items-center justify-center">
                            <span className="text-[9px] font-bold text-ink-muted">
                               {(subtask.assignee?.initials || '?')}
                            </span>
                          </div>
                        </div>
                      </div>

                      {/* Hover Arrow */}
                      <div className="opacity-0 group-hover:opacity-100 transition-opacity absolute right-2">
                        {/* Could be an arrow icon to indicate "open" */}
                      </div>
                    </motion.div>
                  ))
                )}
              </div>

              {/* Add Subtask Button (Bottom) */}
              <motion.button
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                onClick={() => setIsModalOpen(true)}
                className="
                  w-full mt-3
                  flex items-center justify-center gap-2
                  py-2.5 rounded-xl
                  border border-dashed border-surface-300/50 dark:border-surface-600/50
                  text-ink-muted dark:text-ink-inverse-muted
                  hover:border-accent/50 dark:hover:border-accent-light/50
                  hover:text-accent dark:hover:text-accent-light
                  hover:bg-accent/5 dark:hover:bg-accent-light/5
                  transition-all duration-200
                "
              >
                <PlusIcon className="w-4 h-4" />
                <span className="text-body-sm font-medium">Add subtask</span>
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <SubtaskCreationModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)}
        onCreate={handleCreateSubtask}
      />
    </div>
  )
}

function PriorityBadge({ priority }: { priority: TaskPriority }) {
   const colors = {
    critical: 'text-danger bg-danger/10',
    high: 'text-warning bg-warning/10',
    medium: 'text-info bg-info/10',
    low: 'text-surface-500 bg-surface-100 dark:bg-surface-800',
  }
  return (
    <span className={`px-1.5 py-0.5 rounded text-[10px] uppercase font-bold tracking-wider ${colors[priority]}`}>
      {priority}
    </span>
  )
}
