import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { Task } from '@/pages/types/task'
import { NotionEditor } from '../editor/NotionEditor'
import { 
  Sparkles as SparklesIcon, 
  ListTodo as ChecklistIcon, 
  Check as CheckIcon, 
  ChevronRight as ChevronRightIcon, 
  Plus as PlusIcon,
  Clock as ClockIcon,
  User as UserIcon,
  Flag as FlagIcon
} from 'lucide-react'
import { cn } from '@/utils/cn'
import { TaskPriority } from '@/pages/types/task'

interface DescriptionTabProps {
  task: Task
  onUpdate?: (task: Task) => void
  onTaskClick?: (taskId: string) => void
}

export function DescriptionTab({ task, onUpdate, onTaskClick }: DescriptionTabProps) {
  const [content, setContent] = useState(task.description || '')
  
  const handleEditorChange = (newContent: string) => {
    setContent(newContent)
  }

  const handleSave = () => {
    if (onUpdate) {
        onUpdate({ ...task, description: content })
    }
  }

  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* AI Summary Banner */}
      {task.autoGeneratedSummary && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className={cn(
            "flex-shrink-0",
            "mx-5 mt-4 p-4",
            "rounded-xl",
            "bg-gradient-to-r from-indigo-500/5 to-violet-500/5",
            "border border-indigo-500/10 dark:border-indigo-400/10"
          )}
        >
          <div className="flex items-start gap-3">
            <span className={cn(
              "flex-shrink-0",
              "w-8 h-8 rounded-lg",
              "bg-indigo-500/10 dark:bg-indigo-500/20",
              "flex items-center justify-center",
              "text-indigo-600 dark:text-indigo-400"
            )}>
              <SparklesIcon className="w-4 h-4" />
            </span>
            <div className="flex-1 min-w-0">
              <h4 className={cn(
                "text-[10px] font-bold uppercase tracking-wider",
                "text-indigo-600 dark:text-indigo-400",
                "mb-1"
              )}>
                AI Summary
              </h4>
              <p className={cn(
                "text-body-sm",
                "text-ink-secondary dark:text-ink-inverse-secondary",
                "leading-relaxed"
              )}>
                {task.autoGeneratedSummary}
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Document Editor Area */}
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="p-5">
           <NotionEditor 
             content={content}
             onChange={handleEditorChange}
             onSave={handleSave}
             placeholder="Add a detailed description... Type / for commands"
           />
        </div>
      </div>

      {/* Subtasks Section */}
      <SubtasksSection 
        subtasks={task.subtasks} 
        onUpdate={(newSubtasks) => {
          if (onUpdate) {
            onUpdate({ ...task, subtasks: newSubtasks })
          }
        }}
        onTaskClick={onTaskClick}
      />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// SUBTASKS SECTION - Closed by default, sophisticated design
// ─────────────────────────────────────────────────────────────────────────────

import { SubtaskCreationModal } from '../SubtaskCreationModal'

function SubtasksSection({ 
  subtasks, 
  onUpdate,
  onTaskClick
}: { 
  subtasks: Task['subtasks']
  onUpdate?: (subtasks: Task['subtasks']) => void
  onTaskClick?: (taskId: string) => void 
}) {
  // CLOSED BY DEFAULT as requested
  const [isExpanded, setIsExpanded] = useState(false)
  const [isModalOpen, setIsModalOpen] = useState(false)
  
  const completedCount = subtasks.filter(s => s.completed).length
  const percentage = subtasks.length > 0 ? Math.round((completedCount / subtasks.length) * 100) : 0
  
  const handleToggleSubtask = (id: string) => {
    if (!onUpdate) return
    const updated = subtasks.map(s => s.id === id ? { ...s, completed: !s.completed } : s)
    onUpdate(updated)
  }

  const handleCreateSubtask = (title: string, priority?: TaskPriority) => {
    if (!onUpdate) return
    const newSubtask: Task['subtasks'][0] = {
      id: crypto.randomUUID(),
      title,
      completed: false,
      order: subtasks.length,
      priority,
    }
    onUpdate([...subtasks, newSubtask])
  }
  
  return (
    <div className={cn(
      "flex-shrink-0",
      "border-t border-surface-200 dark:border-surface-800",
      "bg-surface-50/50 dark:bg-surface-850/50"
    )}>
      {/* Collapsible Header - More sophisticated design */}
      <div className={cn(
        "flex items-center justify-between",
        "px-5 py-3",
        "cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-800/50",
        "transition-colors duration-200"
      )}
      onClick={() => setIsExpanded(!isExpanded)}
      >
        <div className="flex items-center gap-3">
          <motion.div
            animate={{ rotate: isExpanded ? 90 : 0 }}
            transition={{ duration: 0.2 }}
            className="text-ink-muted dark:text-ink-inverse-muted"
          >
            <ChevronRightIcon className="w-4 h-4" />
          </motion.div>
          
          <div className={cn(
            "w-8 h-8 rounded-lg",
            "bg-indigo-500/10 dark:bg-indigo-500/20",
            "flex items-center justify-center",
            "text-indigo-600 dark:text-indigo-400"
          )}>
            <ChecklistIcon className="w-4 h-4" />
          </div>
          
          <div className="flex flex-col">
            <span className="text-body-sm font-medium text-ink dark:text-ink-inverse">
              Subtasks
            </span>
            <span className="text-[10px] text-ink-muted dark:text-ink-inverse-muted">
              {completedCount} of {subtasks.length} completed
            </span>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Progress indicator */}
          <div className="flex items-center gap-2">
            <div className="w-20 h-1.5 rounded-full bg-surface-200 dark:bg-surface-700 overflow-hidden">
              <div 
                className={cn(
                  "h-full rounded-full transition-all duration-500",
                  percentage === 100 
                    ? 'bg-gradient-to-r from-indigo-500 to-violet-500' 
                    : 'bg-indigo-500'
                )}
                style={{ width: `${percentage}%` }}
              />
            </div>
            <span className={cn(
              "text-[11px] font-medium",
              percentage === 100 
                ? 'text-indigo-600 dark:text-indigo-400'
                : 'text-ink-muted dark:text-ink-inverse-muted'
            )}>
              {percentage}%
            </span>
          </div>
          
          {/* Add button */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={(e) => {
              e.stopPropagation()
              setIsModalOpen(true)
            }}
            className={cn(
              "p-1.5 rounded-md",
              "text-ink-muted hover:text-indigo-600",
              "hover:bg-indigo-500/10",
              "transition-colors"
            )}
          >
            <PlusIcon className="w-4 h-4" />
          </motion.button>
        </div>
      </div>

      {/* Collapsible Content */}
      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="px-5 pb-4">
              {/* Subtask List - More detailed and sophisticated */}
              <div className="space-y-2 mt-2">
                {subtasks.length === 0 ? (
                  <div className={cn(
                    "text-center py-8",
                    "border border-dashed border-surface-200 dark:border-surface-700",
                    "rounded-xl"
                  )}>
                    <ChecklistIcon className="w-8 h-8 mx-auto mb-2 text-ink-muted/30" />
                    <p className="text-body-sm text-ink-muted dark:text-ink-inverse-muted">
                      No subtasks yet
                    </p>
                    <p className="text-[11px] text-ink-muted/60 mt-1">
                      Add subtasks to break down this work
                    </p>
                  </div>
                ) : (
                  subtasks.map((subtask, index) => (
                    <motion.div
                      key={subtask.id}
                      initial={{ opacity: 0, x: -8 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.03 }}
                      onClick={() => onTaskClick?.(subtask.id)}
                      className={cn(
                        "group",
                        "flex items-center gap-3",
                        "p-3 rounded-xl",
                        "bg-surface-0 dark:bg-surface-900",
                        "border border-surface-200 dark:border-surface-800",
                        "hover:border-indigo-300 dark:hover:border-indigo-700",
                        "hover:shadow-sm",
                        "transition-all duration-200",
                        "cursor-pointer"
                      )}
                    >
                      {/* Checkbox */}
                      <motion.button
                        whileTap={{ scale: 0.9 }}
                        onClick={(e) => {
                          e.stopPropagation()
                          handleToggleSubtask(subtask.id)
                        }}
                        className={cn(
                          "flex-shrink-0",
                          "w-5 h-5 rounded-md",
                          "flex items-center justify-center",
                          "border-2",
                          "transition-colors duration-200",
                          subtask.completed
                            ? 'bg-indigo-500 border-indigo-500'
                            : 'border-surface-300 dark:border-surface-600 group-hover:border-indigo-400'
                        )}
                      >
                        {subtask.completed && (
                          <CheckIcon className="w-3.5 h-3.5 text-white" strokeWidth={3} />
                        )}
                      </motion.button>
                      
                      {/* Content - More detailed */}
                      <div className="flex-1 min-w-0">
                        <span className={cn(
                          "block text-sm font-medium",
                          subtask.completed
                            ? 'text-ink-muted dark:text-ink-inverse-muted line-through'
                            : 'text-ink dark:text-ink-inverse'
                        )}>
                          {subtask.title}
                        </span>
                        
                        {/* Subtask metadata row */}
                        <div className="flex items-center gap-3 mt-1">
                          {subtask.estimatedTime && (
                            <span className="flex items-center gap-1 text-[10px] text-ink-muted">
                              <ClockIcon className="w-3 h-3" />
                              {subtask.estimatedTime}m
                            </span>
                          )}
                          {subtask.assignee && (
                            <span className="flex items-center gap-1 text-[10px] text-ink-muted">
                              <UserIcon className="w-3 h-3" />
                              {subtask.assignee.name}
                            </span>
                          )}
                        </div>
                      </div>

                      {/* Right side metadata */}
                      <div className="flex items-center gap-2">
                        {subtask.priority && (
                          <PriorityIndicator priority={subtask.priority} />
                        )}
                        {subtask.assignee && (
                          <div className={cn(
                            "w-6 h-6 rounded-full",
                            "bg-gradient-to-br from-indigo-500 to-violet-600",
                            "flex items-center justify-center",
                            "text-[9px] font-bold text-white"
                          )}>
                            {subtask.assignee.initials}
                          </div>
                        )}
                      </div>
                    </motion.div>
                  ))
                )}
              </div>

              {/* Add Subtask Button */}
              <motion.button
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                onClick={() => setIsModalOpen(true)}
                className={cn(
                  "w-full mt-3",
                  "flex items-center justify-center gap-2",
                  "py-2.5 rounded-xl",
                  "border border-dashed border-surface-300 dark:border-surface-600",
                  "text-ink-muted dark:text-ink-inverse-muted",
                  "hover:border-indigo-400 dark:hover:border-indigo-600",
                  "hover:text-indigo-600 dark:hover:text-indigo-400",
                  "hover:bg-indigo-500/5",
                  "transition-all duration-200"
                )}
              >
                <PlusIcon className="w-4 h-4" />
                <span className="text-body-sm font-medium">Add subtask</span>
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <SubtaskCreationModal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)}
        onCreate={handleCreateSubtask}
      />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// PRIORITY INDICATOR - Subtle inline indicator
// ─────────────────────────────────────────────────────────────────────────────

function PriorityIndicator({ priority }: { priority: TaskPriority }) {
  const config = {
    critical: { color: 'bg-violet-500', label: 'Critical' },
    high: { color: 'bg-indigo-500', label: 'High' },
    medium: { color: 'bg-indigo-400', label: 'Medium' },
    low: { color: 'bg-surface-400', label: 'Low' },
  }
  
  const { color, label } = config[priority]
  
  return (
    <div className="flex items-center gap-1" title={label}>
      <FlagIcon className={cn("w-3 h-3", color.replace('bg-', 'text-'))} />
    </div>
  )
}


