import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import type { Task } from '@/types/task'

interface DescriptionTabProps {
  task: Task
  onUpdate?: (task: Task) => void
}

/**
 * Description Tab
 * 
 * This tab is designed to integrate with the Zoom Document SDK for 
 * rich document editing. For now, it provides a placeholder that can
 * be enhanced with the actual SDK integration.
 * 
 * Features planned:
 * - Zoom Document SDK integration for collaborative editing
 * - Version history with audit trail
 * - Template snippets via slash commands
 * - AI-generated summary at the top
 */
export function DescriptionTab({ task }: DescriptionTabProps) {
  const hasDescription = task.description && task.description.trim().length > 0
  
  return (
    <div className="h-full flex flex-col overflow-hidden">
      {/* AI Summary Banner */}
      {task.autoGeneratedSummary && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="
            flex-shrink-0
            mx-6 mt-4 p-4
            rounded-xl
            bg-gradient-to-r from-accent/5 via-accent/10 to-accent/5
            dark:from-accent-light/5 dark:via-accent-light/10 dark:to-accent-light/5
            border border-accent/10 dark:border-accent-light/10
          "
        >
          <div className="flex items-start gap-3">
            <span className="
              flex-shrink-0
              w-8 h-8 rounded-lg
              bg-accent/10 dark:bg-accent-light/10
              flex items-center justify-center
            ">
              <SparklesIcon className="w-4 h-4 text-accent dark:text-accent-light" />
            </span>
            <div className="flex-1 min-w-0">
              <h4 className="
                text-label uppercase tracking-wider
                text-accent dark:text-accent-light
                mb-1
              ">
                AI Summary
              </h4>
              <p className="
                text-body-sm
                text-ink-secondary dark:text-ink-inverse-secondary
                leading-relaxed
              ">
                {task.autoGeneratedSummary}
              </p>
            </div>
          </div>
        </motion.div>
      )}

      {/* Document Editor Area */}
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="p-6">
          {hasDescription ? (
            <DescriptionEditor content={task.description!} />
          ) : (
            <EmptyDescriptionState />
          )}
        </div>
      </div>

      {/* Subtasks Section */}
      {task.subtasks.length > 0 && (
        <SubtasksSection subtasks={task.subtasks} />
      )}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// DESCRIPTION EDITOR
// ─────────────────────────────────────────────────────────────────────────────

function DescriptionEditor({ content }: { content: string }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="prose prose-lg dark:prose-invert max-w-none"
    >
      {/* 
        Placeholder for Zoom Document SDK integration.
        Currently renders the description as plain text.
        
        TODO: Integrate Zoom Document SDK with:
        - zd.Docs.create() for collaborative editing
        - Real-time sync via WebSocket
        - Version history tracking
        - Slash command templates
      */}
      <div className="
        min-h-[200px]
        p-4 rounded-xl
        bg-surface-50/50 dark:bg-surface-800/30
        border border-surface-200 dark:border-surface-700
        focus-within:border-accent dark:focus-within:border-accent-light
        transition-colors duration-200
      ">
        <div 
          className="
            text-body-md
            text-ink dark:text-ink-inverse
            leading-relaxed
            whitespace-pre-wrap
          "
        >
          {content}
        </div>
        
        {/* Editor Toolbar Hint */}
        <div className="
          mt-6 pt-4
          border-t border-surface-200 dark:border-surface-700
          flex items-center gap-2
          text-body-xs text-ink-muted dark:text-ink-inverse-muted
        ">
          <kbd className="
            px-2 py-1 rounded
            bg-surface-200 dark:bg-surface-700
            text-[10px] font-mono
          ">/</kbd>
          <span>for commands</span>
          <span className="mx-2">•</span>
          <kbd className="
            px-2 py-1 rounded
            bg-surface-200 dark:bg-surface-700
            text-[10px] font-mono
          ">⌘ + S</kbd>
          <span>to save</span>
        </div>
      </div>
    </motion.div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// EMPTY STATE
// ─────────────────────────────────────────────────────────────────────────────

function EmptyDescriptionState() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="
        min-h-[300px]
        flex flex-col items-center justify-center
        p-8 rounded-xl
        border-2 border-dashed border-surface-200 dark:border-surface-700
      "
    >
      <div className="
        w-16 h-16 mb-4 rounded-2xl
        bg-surface-100 dark:bg-surface-800
        flex items-center justify-center
      ">
        <DocumentIcon className="w-8 h-8 text-ink-muted dark:text-ink-inverse-muted" />
      </div>
      
      <h3 className="
        text-body-lg font-medium
        text-ink dark:text-ink-inverse
        mb-2
      ">
        No description yet
      </h3>
      
      <p className="
        text-body-sm text-center
        text-ink-muted dark:text-ink-inverse-muted
        max-w-md mb-6
      ">
        Add a detailed description to help team members understand what needs to be done.
        You can use rich text formatting, checklists, and more.
      </p>

      <motion.button
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        className="
          flex items-center gap-2
          px-4 py-2.5 rounded-lg
          bg-accent dark:bg-accent-light
          text-white
          text-body-sm font-medium
          hover:shadow-glow-accent
          transition-shadow duration-200
        "
      >
        <PlusIcon className="w-4 h-4" />
        Add description
      </motion.button>
      
      <div className="
        mt-8 flex items-center gap-4
        text-body-xs text-ink-muted dark:text-ink-inverse-muted
      ">
        <span className="flex items-center gap-1.5">
          <SparklesIcon className="w-3.5 h-3.5" />
          AI can help write descriptions
        </span>
        <span>•</span>
        <span className="flex items-center gap-1.5">
          <TemplateIcon className="w-3.5 h-3.5" />
          Use templates
        </span>
      </div>
    </motion.div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// SUBTASKS SECTION (Collapsible)
// ─────────────────────────────────────────────────────────────────────────────

function SubtasksSection({ subtasks }: { subtasks: Task['subtasks'] }) {
  const [isExpanded, setIsExpanded] = useState(true)
  const completedCount = subtasks.filter(s => s.completed).length
  const percentage = Math.round((completedCount / subtasks.length) * 100)
  
  return (
    <div className="
      flex-shrink-0
      border-t border-surface-200 dark:border-surface-700
      bg-surface-50/50 dark:bg-surface-800/30
    ">
      {/* Collapsible Header */}
      <motion.button
        onClick={() => setIsExpanded(!isExpanded)}
        className="
          w-full px-6 py-4
          flex items-center justify-between
          hover:bg-surface-100/50 dark:hover:bg-surface-700/30
          transition-colors duration-200
          cursor-pointer
        "
        whileTap={{ scale: 0.995 }}
      >
        <div className="flex items-center gap-2">
          {/* Chevron indicator */}
          <motion.div
            animate={{ rotate: isExpanded ? 90 : 0 }}
            transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
          >
            <ChevronRightIcon className="w-4 h-4 text-ink-muted dark:text-ink-inverse-muted" />
          </motion.div>
          <ChecklistIcon className="w-4 h-4 text-ink-muted dark:text-ink-inverse-muted" />
          <span className="text-body-sm font-medium text-ink dark:text-ink-inverse">
            Sub-Tasks
          </span>
          <span className="
            px-2 py-0.5 rounded
            bg-surface-200 dark:bg-surface-700
            text-label
            text-ink-muted dark:text-ink-inverse-muted
          ">
            {completedCount}/{subtasks.length}
          </span>
        </div>
        <span className="text-body-sm font-medium text-accent dark:text-accent-light">
          {percentage}%
        </span>
      </motion.button>

      {/* Collapsible Content */}
      <AnimatePresence initial={false}>
        {isExpanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-4">
              {/* Progress Bar */}
              <div className="h-1.5 rounded-full bg-surface-200 dark:bg-surface-700 mb-4 overflow-hidden">
                <motion.div
                  className={`h-full rounded-full ${percentage === 100 ? 'bg-success' : 'bg-accent dark:bg-accent-light'}`}
                  initial={{ width: 0 }}
                  animate={{ width: `${percentage}%` }}
                  transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
                />
              </div>

              {/* Subtask List */}
              <div className="space-y-2 max-h-48 overflow-y-auto scrollbar-thin">
                {subtasks.map((subtask, index) => (
                  <motion.div
                    key={subtask.id}
                    initial={{ opacity: 0, x: -8 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.05 }}
                    className="
                      flex items-center gap-3
                      p-2 rounded-lg
                      hover:bg-surface-100 dark:hover:bg-surface-700/50
                      transition-colors duration-200
                      group cursor-pointer
                    "
                  >
                    <motion.button
                      whileTap={{ scale: 0.9 }}
                      className={`
                        w-5 h-5 rounded-md
                        flex items-center justify-center
                        border-2
                        transition-colors duration-200
                        ${subtask.completed
                          ? 'bg-success border-success'
                          : 'border-surface-300 dark:border-surface-600 group-hover:border-accent dark:group-hover:border-accent-light'
                        }
                      `}
                    >
                      {subtask.completed && (
                        <CheckIcon className="w-3 h-3 text-white" />
                      )}
                    </motion.button>
                    
                    <span className={`
                      flex-1 text-body-sm
                      ${subtask.completed
                        ? 'text-ink-muted dark:text-ink-inverse-muted line-through'
                        : 'text-ink dark:text-ink-inverse'
                      }
                    `}>
                      {subtask.title}
                    </span>
                  </motion.div>
                ))}
              </div>

              {/* Add Subtask */}
              <motion.button
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                className="
                  w-full mt-3
                  flex items-center justify-center gap-2
                  py-2 rounded-lg
                  border border-dashed border-surface-300 dark:border-surface-600
                  text-ink-muted dark:text-ink-inverse-muted
                  hover:border-accent/50 dark:hover:border-accent-light/50
                  hover:text-accent dark:hover:text-accent-light
                  transition-all duration-200
                "
              >
                <PlusIcon className="w-4 h-4" />
                <span className="text-body-sm">Add subtask</span>
              </motion.button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// ICONS
// ─────────────────────────────────────────────────────────────────────────────

function SparklesIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3l1.912 5.813a2 2 0 0 0 1.275 1.275L21 12l-5.813 1.912a2 2 0 0 0-1.275 1.275L12 21l-1.912-5.813a2 2 0 0 0-1.275-1.275L3 12l5.813-1.912a2 2 0 0 0 1.275-1.275L12 3z" />
    </svg>
  )
}

function DocumentIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
      <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
      <polyline points="14 2 14 8 20 8" />
      <line x1="16" y1="13" x2="8" y2="13" />
      <line x1="16" y1="17" x2="8" y2="17" />
    </svg>
  )
}

function PlusIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
      <line x1="12" y1="5" x2="12" y2="19" />
      <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
  )
}

function TemplateIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
      <rect x="3" y="3" width="18" height="18" rx="2" />
      <line x1="3" y1="9" x2="21" y2="9" />
      <line x1="9" y1="21" x2="9" y2="9" />
    </svg>
  )
}

function ChecklistIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round">
      <line x1="10" y1="6" x2="21" y2="6" />
      <line x1="10" y1="12" x2="21" y2="12" />
      <line x1="10" y1="18" x2="21" y2="18" />
      <polyline points="3 6 4 7 6 5" />
      <polyline points="3 12 4 13 6 11" />
      <polyline points="3 18 4 19 6 17" />
    </svg>
  )
}

function CheckIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}

function ChevronRightIcon({ className }: { className?: string }) {
  return (
    <svg className={className || "w-4 h-4"} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="9 18 15 12 9 6" />
    </svg>
  )
}

